"""Domain models for Skin Shortcuts."""

from __future__ import annotations

from .background import (
    Background,
    BackgroundConfig,
    BackgroundGroup,
    BackgroundType,
    BrowseSource,
    PlaylistSource,
)
from .menu import (
    Action,
    Content,
    DefaultAction,
    IconSource,
    Menu,
    MenuAllow,
    MenuConfig,
    MenuItem,
    Shortcut,
    ShortcutGroup,
)
from .property import (
    ButtonMapping,
    FallbackRule,
    IconVariant,
    PropertyFallback,
    PropertySchema,
    SchemaOption,
    SchemaProperty,
)
from .template import (
    BuildMode,
    IncludeDefinition,
    ItemsDefinition,
    ListItem,
    Preset,
    PresetValues,
    PropertyGroup,
    PropertyGroupReference,
    SubmenuTemplate,
    Template,
    TemplateParam,
    TemplateProperty,
    TemplateSchema,
    TemplateVar,
    VariableDefinition,
    VariableGroup,
    VariableGroupReference,
    VariableReference,
)
from .widget import Widget, WidgetConfig, WidgetGroup

__all__ = [
    "Action",
    "Background",
    "BackgroundConfig",
    "BackgroundGroup",
    "BackgroundType",
    "BrowseSource",
    "BuildMode",
    "ButtonMapping",
    "Content",
    "DefaultAction",
    "FallbackRule",
    "ShortcutGroup",
    "IconSource",
    "IconVariant",
    "IncludeDefinition",
    "ItemsDefinition",
    "ListItem",
    "Menu",
    "MenuAllow",
    "MenuConfig",
    "MenuItem",
    "PlaylistSource",
    "Preset",
    "PresetValues",
    "PropertyFallback",
    "PropertyGroup",
    "PropertyGroupReference",
    "PropertySchema",
    "SchemaOption",
    "SchemaProperty",
    "Shortcut",
    "SubmenuTemplate",
    "Template",
    "TemplateParam",
    "TemplateProperty",
    "TemplateSchema",
    "TemplateVar",
    "VariableDefinition",
    "VariableGroup",
    "VariableGroupReference",
    "VariableReference",
    "Widget",
    "WidgetConfig",
    "WidgetGroup",
]
